<?php

	function adjacent_states()
	{

		return
			array(
			"Alabama"        => array("Florida","Georgia","Mississippi","Tennessee"),
			"Alaska"         => array(),
			"Arizona"        => array("California","Colorado","Nevada","New Mexico","Utah"),
			"Arkansas"       => array("Louisiana","Mississippi","Missouri","Oklahoma","Tennessee","Texas"),
			"California"     => array("Oregon", "Nevada","Arizona"),
			"Colorado"       => array("Arizona","Kansas","Oklahoma","Nebraska","New Mexico","Utah","Wyoming"),
			"Connecticut"    => array("Massachussetts","New York","Rhode Island"),
			"Delaware"       => array("Maryland", "New Jersey", "Pennsylvania"),
			"District of Columbia" => array("Maryland", "Virginia"),
			"Washington DC" => array("Maryland", "Virginia"),
			"Florida"        => array("Alabama","Georgia"),
			"Georgia"        => array("Alabama","Florida","North Carolina","South Carolina","Tennessee"),
			"Hawaii"         => array(),
			"Idaho"          => array("Montana","Nevada","Oregon","Utah","Washington","Wyoming"),
			"Illinois"       => array("Indiana","Iowa","Kentucky","Missouri","Wisconsin"),
			"Indiana"        => array("Illinois","Kentucky","Michigan","Ohio"),
			"Iowa"           => array("Illinois", "Kansas", "Minnesota", "Missouri", "Nebraska", "South Dakota", "Wisconsin"),
			"Kansas"         => array("Colorado", "Missouri","Nebraska","Oklahoma"),
			"Kentucky"       => array("Illinois", "Illinois", "Missouri", "North Carolina","Ohio", "Tennessee", "Virginia", "West Virginia"),
			"Louisiana"      => array("Arkansas", "Mississippi", "Texas"),
			"Maine"          => array("New Hampshire"),
			"Maryland"       => array("Delaware","Pennsylvania","Virginia","West Virgina"),
			"Massachusetts"  => array("Connecticut","New Hampshire","New York","Rhode Island","Vermont"),
			"Michigan"       => array("Indiana","Ohio","Wisconsin"),
			"Minnesota"      => array("Iowa", "North Dakota", "South Dakota", "Wisconsin"),
			"Mississippi"    => array("Alabama", "Arkansas", "Louisiana", "Tennessee"),
			"Missouri"       => array("Arkansas","Illinois", "Iowa","Kansas","Kentucky","Nebraska","Oklahoma","Tennessee"),
			"Montana"        => array("Idaho", "North Dakota", "South Dakota", "Wyoming"),
			"Nebraska"       => array("Colorado", "Iowa", "Kansas", "South Dakota","Wyoming"),
			"Nevada"         => array("Arizona", "California", "Idaho", "Oregon", "Utah"),
			"New Hampshire"  => array("Maine", "Massachussetts", "Vermont"),
			"New Jersey"     => array("Connecticut", "Delaware", "New York", "Pennsylvania"),
			"New Mexico"     => array("Arizona", "Colorado", "Kansas", "Oklahoma", "Texas", "Utah"),
			"New York"       => array("Connecticut", "Massachussetts", "Pennsylvania", "Vermont"),
			"North Carolina" => array("South Carolina","Tennessee", "Virginia"),
			"North Dakota"   => array("Minnesota", "Montana", "South Dakota"),
			"Ohio"           => array("Indiana", "Kentucky", "Michigan", "Pennsylvania", "West Virgina"),
			"Oklahoma"       => array("Arkansas", "Colorado", "Kansas", "Montana", "New Mexico", "Texas"),
			"Oregon"         => array("California", "Idaho", "Nevada", "Washington"),
			"Pennsylvania"   => array("Delaware", "Maryland", "New Jersey", "New York", "Ohio", "West Virgina"),
			"Rhode Island"   => array("Connecticut", "Massachusetts"),
			"South Carolina" => array("Georgia", "North Carolina", "Tennessee"),
			"South Dakota"   => array("Iowa","Minnesota", "Montana", "Nebraska", "North Dakota", "Wyoming"),
			"Tennessee"      => array("Alabama", "Arkansas", "Georgia", "Kentucky", "Mississippi", "Missouri", "North Carolina", "Virginia"),
			"Texas"          => array("Arkansas", "Louisiana", "New Mexico", "Oklahoma"),
			"Utah"           => array("Arizona", "Colorado", "Idaho", "Nevada", "New Mexico", "Wyoming"),
			"Vermont"        => array("Massachussetts", "New Hampshire", "New York"),
			"Virginia"       => array("Delaware", "Kentucky", "Maryland", "North Carolina", "Pennsylvania", "Tennessee", "West Virgina"),
			"Washington"     => array("Idaho", "Oregon"),
			"West Virginia"  => array("Kentucky", "Pennsylvania", "Ohio", "Virginia"),
			"Wisconsin"      => array("Illinois", "Iowa", "Michigan", "Minnesota"),
			"Wyoming"        => array("Colorado", "Idaho", "Montana", "South Dakota", "Utah")
		);
	}

	function adjabrev()
	{
		return array(
			"AL" => array("FL","GA","MS","TN"),
			"AK" => array(),
			"AZ" => array("CA","CO","NV","NM","UT"),
			"AR" => array("LA","MS","MO","OK","TN","TX"),
			"CA" => array("OR", "NV","AZ"),
			"CO" => array("AZ","KS","OK","NE","NM","UT","WY"),
			"CT" => array("MA","NY","RI"),
			"DE" => array("MD", "NJ", "PA"),
			"DC" => array("MD", "VA"),
			"FL" => array("AL","GA"),
			"GA" => array("AL","FL","NC","SC","TN"),
			"HI" => array(),
			"ID" => array("MT","NV","OR","UT","WA","WY"),
			"IL" => array("IN","IA","KY","MO","WI"),
			"IN" => array("IL","KY","MI","OH"),
			"IA" => array("IL", "KS", "MN", "MO", "NE", "SD", "WI"),
			"KS" => array("CO", "MO","NE","OK"),
			"KY" => array("IL", "IL", "MO", "NC","OH", "TN", "VA", "WV"),
			"LA" => array("AR", "MS", "TX"),
			"ME" => array("NH"),
			"MD" => array("DE","PA","VA","WV"),
			"MA" => array("CT","NH","NY","RI","VT"),
			"MI" => array("IN","OH","WI"),
			"MN" => array("IA", "ND", "SD", "WI"),
			"MS" => array("AL", "AR", "LA", "TN"),
			"MO" => array("AR","IL", "IA","KS","KY","NE","OK","TN"),
			"MT" => array("ID", "ND", "SD", "WY"),
			"NE" => array("CO", "IA", "KS", "SD","WY"),
			"NV" => array("AZ", "CA", "ID", "OR", "UT"),
			"NH" => array("ME", "MA", "VT"),
			"NJ" => array("CT", "DE", "NY", "PA"),
			"NM" => array("AZ", "CO", "KS", "OK", "TX", "UT"),
			"NY" => array("CT", "MA", "PA", "VT"),
			"NC" => array("SC","TN", "VA"),
			"ND" => array("MN", "MT", "SD"),
			"OH" => array("IN", "KY", "MI", "PA", "WV"),
			"OK" => array("AR", "CO", "KS", "MT", "NM", "TX"),
			"OR" => array("CA", "ID", "NV", "WA"),
			"PA" => array("DE", "MD", "NJ", "NY", "OH", "WV"),
			"RI" => array("CT", "MA"),
			"SC" => array("GA", "NC", "TN"),
			"SD" => array("IA","MN", "MT", "NE", "ND", "WY"),
			"TN" => array("AL", "AR", "GA", "KY", "MS", "MO", "NC", "VA"),
			"TX" => array("AR", "LA", "NM", "OK"),
			"UT" => array("AZ", "CO", "ID", "NV", "NM", "WY"),
			"VT" => array("MA", "NH", "NY"),
			"VA" => array("DE", "KY", "MD", "NC", "PA", "TN", "WV"),
			"WA" => array("ID", "OR"),
			"WV" => array("KY", "PA", "OH", "VA"),
			"WI" => array("IL", "IA", "MI", "MN"),
			"WY" => array("CO", "ID", "MT", "SD", "UT")
		);
	}

	function states_full_abbrv()
	{
		return array(
			'Alabama'=>'AL',
			'Alaska'=>'AK',
			'Arizona'=>'AZ',
			'Arkansas'=>'AR',
			'California'=>'CA',
			'Colorado'=>'CO',
			'Connecticut'=>'CT',
			'Delaware'=>'DE',
			'Florida'=>'FL',
			'Georgia'=>'GA',
			'Hawaii'=>'HI',
			'Idaho'=>'ID',
			'Illinois'=>'IL',
			'Indiana'=>'IN',
			'Iowa'=>'IA',
			'Kansas'=>'KS',
			'Kentucky'=>'KY',
			'Louisiana'=>'LA',
			'Maine'=>'ME',
			'Maryland'=>'MD',
			'Massachusetts'=>'MA',
			'Michigan'=>'MI',
			'Minnesota'=>'MN',
			'Mississippi'=>'MS',
			'Missouri'=>'MO',
			'Montana'=>'MT',
			'Nebraska'=>'NE',
			'Nevada'=>'NV',
			'New Hampshire'=>'NH',
			'New Jersey'=>'NJ',
			'New Mexico'=>'NM',
			'New York'=>'NY',
			'North Carolina'=>'NC',
			'North Dakota'=>'ND',
			'Ohio'=>'OH',
			'Oklahoma'=>'OK',
			'Oregon'=>'OR',
			'Pennsylvania'=>'PA',
			'Rhode Island'=>'RI',
			'South Carolina'=>'SC',
			'South Dakota'=>'SD',
			'Tennessee'=>'TN',
			'Texas'=>'TX',
			'Utah'=>'UT',
			'Vermont'=>'VT',
			'Virginia'=>'VA',
			'Washington'=>'WA',
			'Washington DC'=>'DC',
			'West Virginia'=>'WV',
			'Wisconsin'=>'WI',
			'Wyoming'=>'WY'
		);
	}

	function state_fullname($state)
	{
		$us_states = array(
			'AL'=>'Alabama',
			'AK'=>'Alaska',
			'AZ'=>'Arizona',
			'AR'=>'Arkansas',
			'CA'=>'California',
			'CO'=>'Colorado',
			'CT'=>'Connecticut',
			'DE'=>'Delaware',
			'DC'=>'Washington DC',
			'FL'=>'Florida',
			'GA'=>'Georgia',
			'HI'=>'Hawaii',
			'ID'=>'Idaho',
			'IL'=>'Illinois',
			'IN'=>'Indiana',
			'IA'=>'Iowa',
			'KS'=>'Kansas',
			'KY'=>'Kentucky',
			'LA'=>'Louisiana',
			'ME'=>'Maine',
			'MD'=>'Maryland',
			'MA'=>'Massachusetts',
			'MI'=>'Michigan',
			'MN'=>'Minnesota',
			'MS'=>'Mississippi',
			'MO'=>'Missouri',
			'MT'=>'Montana',
			'NE'=>'Nebraska',
			'NV'=>'Nevada',
			'NH'=>'New Hampshire',
			'NJ'=>'New Jersey',
			'NM'=>'New Mexico',
			'NY'=>'New York',
			'NC'=>'North Carolina',
			'ND'=>'North Dakota',
			'OH'=>'Ohio',
			'OK'=>'Oklahoma',
			'OR'=>'Oregon',
			'PA'=>'Pennsylvania',
			'RI'=>'Rhode Island',
			'SC'=>'South Carolina',
			'SD'=>'South Dakota',
			'TN'=>'Tennessee',
			'TX'=>'Texas',
			'UT'=>'Utah',
			'VT'=>'Vermont',
			'VA'=>'Virginia',
			'WA'=>'Washington',
			'WV'=>'West Virginia',
			'WI'=>'Wisconsin',
			'WY'=>'Wyoming',
		);
		return $us_states[$state];
	}

?>
